export const USER_SIGNIN_REQUEST = 'user_signin_request'
export const USER_SIGNIN_SUCCESS = 'user_signin_success'
export const USER_SIGNIN_FAIL = 'user_signin_fail'
export const USER_REGISTER_REQUEST = 'user_register_request'
export const USER_REGISTER_SUCCESS = 'user_register_success'
export const USER_REGISTER_FAIL = 'user_register_fail'